imposters_path: "."
port: 3001
host: "localhost"
proxy:
  url: "http://localhost:8443"
  mode: none
cors:
  methods: []
  headers: []
  exposed_headers: []
  origins: ["*"]
  allow_credentials: true
watcher: false
secure: false